### ISSUE TITLE
high level pokemon near the portal of the nether

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#129]
#### What happens:

i found a lot of pokemons with level 30 and 51 near the portal of the nether in a distance of 5 blocks
#### What you expected to happen:

there shouldn't be high level pokemons there
#### Steps to reproduce:

1.go to the nether

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core:3.7.6
- Pokecube Revival (if applicable):3.6.5
- Pokecube Mobs (if applicable):2.2.2
- Minecraft: 1.9.4
- Forge:1990

**Comment by Thutmose** [comment]
it is probably due to the spawn centers for the nether and the overworld being different, Try changing spawnCentered to false, and delete the spawnLevelFunctions option to let it reset (should regenerate it with the new stuff if it is deleted)
 and see if that makes the ones at the nether about the same level as the ones in the overworld.

**Comment by jochuan** [comment]
it worked
