### ISSUE TITLE
Poke trainers have more than 6 pokemons

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#134]
#### Issue Description:

the trainers are using the same pokemon that was defeated endlessly
#### What happens:

after you defeat all the pokemons of the trainer they still send them without stopping this can be used as easy way to level up your pokemon by players
![2016-08-20_13 46 22](https://cloud.githubusercontent.com/assets/11268912/17832605/95bdf3b4-66dd-11e6-9fac-670bb04c7989.png)
#### What you expected to happen:

they shouldn't have more than 6 pokemon the same should be applied to the player if possible
#### Steps to reproduce:

1randomly fight against trainers

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core:3.7.8
- Pokecube Revival (if applicable):3.6.7
- Pokecube Mobs (if applicable):2.2.2
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
hmm, rather than more than 6, they seem to not be going on cooldown correctly, and are continually reviving and sending out old ones, I will see if I can find a way to get it to happen, then I can fix it, I had it happen once when I was running out of development, but not yet in the development environment.

Definintely something wrong, as they are supposed to warn you they are about to send out a next one before each one they send out.

**Comment by Thutmose** [comment]
This should be fixed for next release.

**Comment by Thutmose** [comment]
Fixed in version I just uploaded to curse.
