### ISSUE TITLE
The moves are disappearing

### ISSUE THREAD

**Issue by Oatibx15** [Thutmose/Pokecube#183]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### What happens:
Iam making a Pokecube roleplay series on my YT, when I build stuff and when I check my pokemon, the moves are becoming Tackle.

#### What you expected to happen:
Still the same move...

#### Steps to reproduce:

1. Iam editing it with a command
2.and setting a MOVE for a Pokemob
3.then I start making an episode
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:                                   ~All of these are latest versions
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.8.9
- Forge:

**Comment by Thutmose** [comment]
I need more detailed instructions on how to get this bug to occur.  I havent been able to replicate this bug reliably, if you can give me exact steps, then I should be able to fix it.

**Comment by Thutmose** [comment]
This has been fixed in the 1.10.2+ versions of pokecube.

**Comment by Oatibx15** [comment]
Iam making a roleplay with PokeCube, I dont have to level up the Pokemob to
get it moves, I just do the(I forgot the command, Its the command where you
edit moves, abilities, etc) And when I leave and join back the world, the
Moves disappears and replaced with Tackle. IDK if it was fixed but I
haven't updated the mod in a very long time. BTW I think this mod is better
than pixelmon even though pixelmon is more popular. Its just I can play
this mod without lag and out of space, This mod is good for bad computes
xD. And also the feature that makes you battle a pokemon by yourself. BTW
Can you change the Cries to their real voices like from the anime and put
like a 20% chance of it saying the name in a minute because I can hear the
cries over and over and its so annoying.

**Comment by Thutmose** [comment]
wild animals make sounds much more like the ones that i use, and make an awfully large number of noises, these sounds are their real cries from the games, the anime sounds are the fake ones, as they were just done so that children would be able to remember which pokemon they were looking at (since they don't have nametags in the anime).

that being said, you can change the sounds with a resource pack if you want to.  

I can try to add a config option for how often they make sounds though, currently they are exactly the same as vanilla animals/mobs for the sounds, but I can see if I can modify how often they make them.
