### ISSUE TITLE
Feature Request - Player to Pokecube Damage Controller

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Thutmose/Pokecube#243]
I just added guns to my server but the guns are extremely good at killing pokecubes and I was wondering if you could add a player to poke-cube damage calculator.

**Comment by Thutmose** [comment]
pokecubes shouldn't be able to take damage at all? 

if you meant Pokemobs instead of pokecube, there is already a config option called playerToPokemobDamageScale

If so, if the guns deal that much damage, it is probably a balance choice on the part of the gun mod, and you should probably check for configs for it.

**Comment by P3rf3ctXZer0** [comment]
playerToPokemob I will look into it.
