### ISSUE TITLE
Mareep shiny texture

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#25]
#### Issue Description:

the shiny texture of mareep should be pink but the dying code make it pink and yellow and you said something about making a especial case for making it defaults to pink
#### What happens:

![image](https://cloud.githubusercontent.com/assets/11268912/15077927/1cd721cc-1387-11e6-893b-f047e4c9c12f.png)
#### What you expected to happen:

the texture should be pink
#### Steps to reproduce:

1.just see a shiny mareep

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core:2.3.39
- Pokecube Revival (if applicable):2.2.16.k
- Pokecube Mobs (if applicable):1.1.21
- Minecraft: 1.8.9
- Forge:all versions i think

**Comment by Thutmose** [comment]
Right, I forgot about trying to make a way to load in special cases for shiny dyeable pokemobs.  I will try to see about doing this soon.

One thing to note: when I do make that change, it might not affect the mareep in that gui, as i am not sure if it will automatically change the value in the box called "info", if you change that number, it will change the colour of the mareep.  I will see about making it so that when the button to toggle shiny is pressed, that it will reset that number to the new standard.

**Comment by jochuan** [comment]
ok thanks
