### ISSUE TITLE
question

### ISSUE THREAD

**Issue by arata00** [Thutmose/Pokecube#251]
recently was looking and realized that there were some pokemon that were not on the list of the ones that are missing being added, they are:

full moon lunala
radiant sun solgaleo
![download](https://user-images.githubusercontent.com/32281316/34450697-d45133f6-ecf7-11e7-978f-4b3794cc3673.jpg)

dawn wings necrozma
![download](https://user-images.githubusercontent.com/32281316/34450701-e7266b68-ecf7-11e7-9c2c-727c913f4ac2.jpg)

dusk mane necrozma
![download](https://user-images.githubusercontent.com/32281316/34450705-fbd9cb86-ecf7-11e7-874b-23f9e36c3df0.jpg)

ultra necrozma
![images](https://user-images.githubusercontent.com/32281316/34450708-0e860d08-ecf8-11e7-992f-87b6e2673888.jpg)

I would like to know if they will be added

**Comment by Thutmose** [comment]
This issue belongs in 
https://github.com/Thutmose/Pokecube-Mobs 
or 
https://github.com/Thutmose/Pokecube-Models 

Please re-make it in one of those two, probably the first one, since necrozma needs database entries added.

they will probably be added if I get models for them, I will see about adding the necrozma forms to the database, since they actually have stats for them on Serebii.net, for the others, I will wait till I have models before adding them.
